-- ===========================
-- Create 'cards' table
-- ===========================
CREATE TABLE IF NOT EXISTS cards (
  id CHAR(36) NOT NULL PRIMARY KEY,                        -- Scryfall card ID (UUID)
  oracle_id CHAR(36),
  name VARCHAR(255) NOT NULL,
  lang VARCHAR(10),
  released_at DATE,
  layout VARCHAR(50),
  mana_cost VARCHAR(50),
  cmc DECIMAL(5,2),
  type_line VARCHAR(255),
  oracle_text TEXT,
  power VARCHAR(10),
  toughness VARCHAR(10),
  colors JSON,
  color_identity JSON,
  keywords JSON,
  produced_mana JSON,
  rarity VARCHAR(50),
  set_code VARCHAR(10),
  set_name VARCHAR(255),
  collector_number VARCHAR(50),
  artist VARCHAR(255),
  artist_ids JSON,
  illustration_id CHAR(36),
  flavor_text TEXT,
  full_art BOOLEAN,
  textless BOOLEAN,
  promo BOOLEAN,
  reprint BOOLEAN,
  frame VARCHAR(10),
  border_color VARCHAR(20),
  image_uris JSON,
  legalities JSON,
  games JSON,
  finishes JSON,
  reserved BOOLEAN,
  oversized BOOLEAN,
  foil BOOLEAN,
  nonfoil BOOLEAN,
  digital BOOLEAN,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);